### ISSUE TITLE
Initial record creation

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-Migration#1]
As a first step, I propose creating a Python script which will use the legacy models.py to create YAML files which can be loaded into an instance of the new system. To start with, a FairsharingRecord should be created for every Standard, Policy and Database (not Recommendation) and the appropriate RecordAssociations then created. N.B. Recommendations will be replaced by policies, so the "master_policy" of each recommendation should have "recommends" relation with every record listed in it. 
At this stage it's not necessary to create more than the basic fields for each record, e.g. name, abbreviation, homepage, doi, legacy_ids.

**Comment by ramGranell** [comment]
There exist problems when trying to join tables. It is not work properly, e.g.
    for db in BioDBCore.objects.all():
        for std in db.standardsImplemented.all():
            print(std.type.name)
brings the  following issues
django.core.exceptions.FieldError: Cannot resolve keyword 'databases' into field. Choices are: ...

If I run the same code in biosharing environment with manage.py and it works properly

**Comment by knirirr** [comment]
Migrating to the legacy repository under a migration project closes this ticket.
