### ISSUE TITLE
Migration of record_type: mapping values

### ISSUE THREAD

**Issue by ramGranell** [FAIRsharing/FAIRsharing-Migration#2]
In the document: https://docs.google.com/document/d/1_1HAhrpYw9EUJat0v5L556q4KJtJ9LvjTtRSmcKH3hw/edit#heading=h.sjridcsidvs6
the new record_types are defined. There is not a direct map between the current ones and these new ones.

*For Standard, the five record_types have perfect mapping and it can be done automatically. 
NEW<->OLD
Standards - Models and Formats (S-MF) <-> model
Standards - Terminology Artefacts (S-TA) <-> terminology
Standards - Reporting Guidelines (S-RG) <-> reporting
Standards - Identifier Schema (S-IS) <-> identifier
Standards - Metrics (S-M) <-> metric

*For Policy, there are new four types with the following mapping and doubts to be answered: 
Policy - Funder (P-F) <-> funder
Policy - Journal Publisher (P-JP) <-> funder ?? (1)
Policy - Journal (P-J) <-> funder ?? (1)
Policy - Society (P-S) <-> ?? (2)
?? <->  project (3)

(1) Is it going to be manually performed by curators the division of old "funder" into P-JP and P-J?
(2) Are going to be converted any of the existing policies as P-S? 
(3) Which new record_types are old "project"?

*For Databases, there are new two types with the following mapping and doubts to be answered: 
Database - Knowledge-base (DB-KB) <-> ?? (4)
Database - Repository (DB-R) <-> ?? (4)

(4) Are going to be converted any of the existing databases as DB-KB and DB-R? 

-For Collections there are the following mapping using all the existing record_types
?? <->"Project" (see (3))
?? <-> "Domain"  (5)
P-JP and P-J ?? <->  "Journal" (see (1))
?? <->   "Organization" (6)
(P-F)  <->  "Funder"
 (P-S)  <->  "Society"

(5) Which new record_types are old "domain"?
(6) Which new record_types are old "organization"?

Please, both try to reply the questions and check if the rest of equivalences are correct

**Comment by Drosophilic** [comment]
Hi Ramon, yes this is correct, there are a number of new record types. 
As you have seen, standards are unaffected.

We currently have one record type for databases. This will be split into two types, Knowledge-bases (DB-KB) and Repositories (DB-R), based on the predominant action of the resource (e.g. knowledgebase - synthesises and curates secondary data; repository - stores primary data).

This split will be performed manually by a curator.

We currently have one record type for policies. These currently have a label that defines them as 'journal', 'funder' or 'society'. We are changing this to create different subtypes of policy record.
These are:
Policy - Journal Publisher - this will be derived from the current 'journal' subset
Policy - Journal - this will be derived from the current 'journal' subset
Policy - Funder - this will directly map to the current 'funder' subset
Policy - Society - this will directly map to the current 'society' subset.

Old 'Project' policies may be removed (this is still in flux).

All non-trivial mappings, e.g. Policy journal -> Journal Publisher and Journal will be performed manually by a curator.

We haven't yet addressed the Collections as I'm unclear as to how the model is handling them.

**Comment by knirirr** [comment]
Collections are a instances of FairsharingRecord belonging to the "Collection" FairsharingRegistry via an instance of a RecordType such as "journal", "publisher" &c. &c. (please tell me what you these to be).

**Comment by knirirr** [comment]
This is closed in favour of: https://github.com/ISA-tools/biosharing/issues/1276
